/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoyaltyRouteImport } from './routes/loyalty'
import { Route as InstallRouteImport } from './routes/install'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminFixRouteImport } from './routes/admin-fix'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackOrderIdRouteImport } from './routes/track.$orderId'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoyaltyRoute = LoyaltyRouteImport.update({
  id: '/loyalty',
  path: '/loyalty',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallRoute = InstallRouteImport.update({
  id: '/install',
  path: '/install',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFixRoute = AdminFixRouteImport.update({
  id: '/admin-fix',
  path: '/admin-fix',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderIdRoute = TrackOrderIdRouteImport.update({
  id: '/track/$orderId',
  path: '/track/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-fix': typeof AdminFixRoute
  '/cart': typeof CartRoute
  '/delivery': typeof DeliveryRoute
  '/install': typeof InstallRoute
  '/loyalty': typeof LoyaltyRoute
  '/profile': typeof ProfileRoute
  '/recipes': typeof RecipesRoute
  '/search': typeof SearchRoute
  '/track/$orderId': typeof TrackOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-fix': typeof AdminFixRoute
  '/cart': typeof CartRoute
  '/delivery': typeof DeliveryRoute
  '/install': typeof InstallRoute
  '/loyalty': typeof LoyaltyRoute
  '/profile': typeof ProfileRoute
  '/recipes': typeof RecipesRoute
  '/search': typeof SearchRoute
  '/track/$orderId': typeof TrackOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-fix': typeof AdminFixRoute
  '/cart': typeof CartRoute
  '/delivery': typeof DeliveryRoute
  '/install': typeof InstallRoute
  '/loyalty': typeof LoyaltyRoute
  '/profile': typeof ProfileRoute
  '/recipes': typeof RecipesRoute
  '/search': typeof SearchRoute
  '/track/$orderId': typeof TrackOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-fix'
    | '/cart'
    | '/delivery'
    | '/install'
    | '/loyalty'
    | '/profile'
    | '/recipes'
    | '/search'
    | '/track/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-fix'
    | '/cart'
    | '/delivery'
    | '/install'
    | '/loyalty'
    | '/profile'
    | '/recipes'
    | '/search'
    | '/track/$orderId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-fix'
    | '/cart'
    | '/delivery'
    | '/install'
    | '/loyalty'
    | '/profile'
    | '/recipes'
    | '/search'
    | '/track/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminFixRoute: typeof AdminFixRoute
  CartRoute: typeof CartRoute
  DeliveryRoute: typeof DeliveryRoute
  InstallRoute: typeof InstallRoute
  LoyaltyRoute: typeof LoyaltyRoute
  ProfileRoute: typeof ProfileRoute
  RecipesRoute: typeof RecipesRoute
  SearchRoute: typeof SearchRoute
  TrackOrderIdRoute: typeof TrackOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loyalty': {
      id: '/loyalty'
      path: '/loyalty'
      fullPath: '/loyalty'
      preLoaderRoute: typeof LoyaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/install': {
      id: '/install'
      path: '/install'
      fullPath: '/install'
      preLoaderRoute: typeof InstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-fix': {
      id: '/admin-fix'
      path: '/admin-fix'
      fullPath: '/admin-fix'
      preLoaderRoute: typeof AdminFixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$orderId': {
      id: '/track/$orderId'
      path: '/track/$orderId'
      fullPath: '/track/$orderId'
      preLoaderRoute: typeof TrackOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminFixRoute: AdminFixRoute,
  CartRoute: CartRoute,
  DeliveryRoute: DeliveryRoute,
  InstallRoute: InstallRoute,
  LoyaltyRoute: LoyaltyRoute,
  ProfileRoute: ProfileRoute,
  RecipesRoute: RecipesRoute,
  SearchRoute: SearchRoute,
  TrackOrderIdRoute: TrackOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
