ALTER TABLE flyers ADD COLUMN IF NOT EXISTS layout_type TEXT DEFAULT 'grid-4';
ALTER TABLE flyers ADD COLUMN IF NOT EXISTS header_image TEXT;
ALTER TABLE flyers ADD COLUMN IF NOT EXISTS footer_image TEXT;
ALTER TABLE flyers ADD COLUMN IF NOT EXISTS background_color TEXT DEFAULT '#ffffff';
ALTER TABLE flyers ADD COLUMN IF NOT EXISTS primary_color TEXT DEFAULT '#e11d48';
ALTER TABLE flyers ADD COLUMN IF NOT EXISTS secondary_color TEXT DEFAULT '#fbbf24';
ALTER TABLE flyers ADD COLUMN IF NOT EXISTS products_data JSONB DEFAULT '[]'::jsonb;
ALTER TABLE flyers ADD COLUMN IF NOT EXISTS config JSONB DEFAULT '{}'::jsonb;
